### ISSUE TITLE
How to register?

### ISSUE THREAD

**Issue by thedstrat** [JSv4/Delphic#12]
There doesn't seem to be a place on the login page to register. I also can't figure out where in the filesystem to register. Please advise.

**Comment by JSv4** [comment]
Sry, you have to use the Django admin framework. I need to incorporate an updated setup guide I wrote that tells you how to do this. Will try to get to it after work. For now, check out the Django cookie cutter documentation. You'll have to start by creating a superuser with a command like this:

sudo docker-compose -f local.yml run django python manage.py createsuperuser

Then you can login with those credentials

**Comment by nayutah** [comment]
I use "sudo docker-compose -f local.yml run django python manage.py createsuperuser" to create a user 'admin'. With 'admin', I  login "http://localhost:8000/admin/" successfully, but failed to login the page "http://localhost:3000/". Do they share the same username & password ? 
Thanks for your reply.
