### ISSUE TITLE
Error while creating new collection

### ISSUE THREAD

**Issue by Orolol** [JSv4/Delphic#17]
Hello, thanks for this project ! I'm trying to use it but I ran into an error each time I try to add a collection

```
chat_all_the_docs_local_celeryworker  | [2023-04-23 16:21:38,185: ERROR/ForkPoolWorker-4] Error creating index for collection 6: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /emptycrown/loader-hub/main/loader_hub/library.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff8d6831f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
chat_all_the_docs_local_celeryworker  | [2023-04-23 16:21:38,189: INFO/ForkPoolWorker-4] Task delphic.tasks.index_tasks.create_index[c599e233-f976-4443-8b7a-3a823b204620] succeeded in 10.04079479596112s: False
```

**Comment by JSv4** [comment]
I think this is actually do to LlamaIndex unable to reach the "LlamaHub" where it downloads document loaders from. See here:

See line 17 here: 

https://github.com/jerryjliu/llama_index/blob/c54a6f2bf661135a54a75ffe90b69427d468aa34/gpt_index/readers/download.py#L1-L19

My guess is you might have a network configuration issue. Either your container can't reach the Internet or there's a firewall somewhere stopping the outbound requests. Are you still having the issue? What environment are you running in?

**Comment by JSv4** [comment]
Closing this for now. I do not believe this is an issue with Delphic.
