### ISSUE TITLE
Add a new user in Getting Started or disable authentication?

### ISSUE THREAD

**Issue by ProgramItUp** [JSv4/Delphic#28]
Delphic looks like a cool system but I have not been able to login to it on my localhost.
The [Getting Started](https://github.com/JSv4/Delphic) instructions do not include step by step instructions on how to create a first user.  
I've tried following "Setup Users" without success.
Could you add step-by-step instructions to get past the login screen?
Or, could you add an option when launching the docker compose to disable authentication?

**Comment by medatasci** [comment]
The updated instructions at https://github.com/JSv4/Delphic#first-setup-a-django-superuser resolve the issue.
sudo docker-compose -f local.yml run django python manage.py createsuperuser

**Comment by JSv4** [comment]
Thanks @medatasci. Yes, @ProgramItUp, the instructions should cover this. I update them around the time you opened the issue.

**Comment by ProgramItUp** [comment]
Thanks, the new instructions fixed the error, thanks.
