### ISSUE TITLE
Log Error: Where to get the logger.error() message?

### ISSUE THREAD

**Issue by haimh** [JSv4/Delphic#40]
The problem at hand is the inability to locate the location of the logger.error() message. I has been exploring for a while but has not been able to find it. Recently, I encountered some minor issues while importing a document and indexing (create_index task). Upon looking through the code, I saw the following line:

except Exception as e:
logger.error(f"Error creating index for collection {collection_id}: {e}")
collection.status = CollectionStatus.ERROR
collection.save()

However, they were unable to find where the error was being printed out. They are seeking assistance in resolving this issue.

**Comment by haimh** [comment]
I've dealing with the following file: ./tasks/index_tasks.py.

Anyone have any suggestion or idea?

**Comment by JSv4** [comment]
The log messages typically stream to the console you opened docker-compose in. If you don't see your docker / docker compose logs, that's a docker configuration issue. If you want to send the logs somewhere else, the logger is just a basic Python logger you can configure as you'd like.
