### ISSUE TITLE
Error Creating Index For Collection

### ISSUE THREAD

**Issue by professorDante** [JSv4/Delphic#94]
Unable to create any collections. Getting this error:

`[2023-07-12 23:33:44,790: ERROR/ForkPoolWorker-8] Error creating index for collection 10: Extra data: line 1 column 4 (char 3)
`
I'd love to provide more information, but it's simply impossible to debug, as app uses threading and celery for this part of the code. 

Error thrown from enpoints.py > create_index. 

Trying to upload a single PDF file to a collection.

**Comment by marauder37** [comment]
Basically the LlamaIndex version is super out of date and needs updating. I did a PR for this, the PR has also got a bit old now but will probably still work. https://github.com/JSv4/Delphic/pull/85

For debugging make a management command to reindex stuck collections without celery. Something like: https://gist.github.com/marauder37/b37eeba4399a288a11401c774adc617f

**Comment by professorDante** [comment]
Gotcha. Working from your PR fixed above issue..
